version: '3'

services:
  database:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'tickets'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'